### ISSUE TITLE
Start implementation of user authentication - server side

### ISSUE THREAD

**Issue by mccoyt5** [EECE3093C/team-project-lua-osint-server#11]
# Goal of this issue

Users will have to make an account to use the application and gain access to the different OSINT tools. Therefore, we need to be able to compare a user's username and password inputs to our records so a returning user can login. We will need to add database models, schema, and utilities for CRUD (Create, Read, Update, Delete) to do so.

# Resources

https://fastapi.tiangolo.com/tutorial/sql-databases/

https://fastapi.tiangolo.com/tutorial/dependencies/?h=

https://fastapi.tiangolo.com/tutorial/bigger-applications/?h=

# Deliverables

Must have models, schema, and utilities completed by the iteration 3 deadline.

**Comment by BinniesLite** [comment]
@mccoyt5, would you mind clarifying this issue, is this issue about exposing the api to the front-end or just the logic of the server.

**Comment by mccoyt5** [comment]
@BinniesLite I have updated the description with more information.

**Comment by HeavenlyRain** [comment]
Resolved by #17
