### ISSUE TITLE
Add documentation on how to start container

### ISSUE THREAD

**Issue by BinniesLite** [EECE3093C/team-project-lua-osint-server#12]
### Goal of this issue
Have documentation either in a doc folder or the main root readme on how to build and run the Dockerfile. If this is not applicable or we're fine with running the code on the local development, let me know.

### Deliverables
Everyone should be able to run the local development of the server

**Comment by HeavenlyRain** [comment]
Server and database containers have been modified/changed for a shared network. This eases the process of intercommunication within containers.
