### ISSUE TITLE
Update api documentation for server

### ISSUE THREAD

**Issue by BinniesLite** [EECE3093C/team-project-lua-osint-server#16]
### Goal of this issue 
Create a doc folder and write all the working endpoint in a documentation, it will be faster for the front end if i know which api to call. If you want to work on this issue feel free to add yourself as assignee.

### Deliverables
Either a doc folder to store all the document or in the root README.md update with all the endpoints

*We decided to store the documentation in the root README.md

**Comment by HeavenlyRain** [comment]
# Example:

If we have an api endpoint `/tools/sherlock`

Document the following information:

1. Path: `/tools/sherlock`
2. Restrictions: Authenticated requests only
3. Parameters:
  - `username`: Username that the user wants to look up

**Comment by HeavenlyRain** [comment]
Make sure that for each endpoint, if they share multiple request types indicate so and their different parameters.

**Comment by BinniesLite** [comment]
@HeavenlyRain Would you mind giving me some examples of what I should pass in using that endpoints and some example output?
