### ISSUE TITLE
Update documentation for server routes and middleware

### ISSUE THREAD

**Issue by HeavenlyRain** [EECE3093C/team-project-lua-osint-server#9]
As our application has evolved, the server routes and middleware have also changed, but the documentation has not been updated accordingly. This has led to confusion and difficulties for developers who are trying to understand how the server routes and middleware work.

This issue is to update the documentation for server routes and middleware, to reflect the latest changes in the codebase. The documentation should include descriptions of each route and middleware, including their purpose and any input parameters they accept. It should also provide examples of how to use each route and middleware in the application.

Having up-to-date documentation for server routes and middleware will provide several benefits such as:

- Easier onboarding of new developers who need to understand how the application works.
- Faster development by reducing the time needed to understand the codebase.
- Better maintainability by making it easier to identify and fix issues with the server routes and middleware.

The documentation should be updated in a separate branch and should follow the same style and format as the existing documentation. Once the documentation is updated, it should be reviewed by a team member to ensure that it is accurate, clear, and complete.

**Comment by BinniesLite** [comment]
@HeavenlyRain @mccoyt5 I think it would be awesome to have some type of document that explain which file is doing what and maybe a little guide to FastAPI, if you guys think this is not applicable let me know.

**Comment by HeavenlyRain** [comment]
Relates to #16
